version: '3.8'

services:
  restaurant-postgres:
    image: postgres:15-alpine
    container_name: restaurant_db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: restaurant_db
    ports:
      - '5433:5432'
    volumes:
      - restaurant_postgres_data:/var/lib/postgresql/data

  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_microservice
    restart: always
    ports:
      - '3334:3334'
    environment:
      PORT: 3334
      HOST: 0.0.0.0
      NODE_ENV: production
      APP_KEY: RESTAURANT_SERVICE_SECRET_APP_KEY_12345
      APP_NAME: restaurant-service
      DB_CONNECTION: pg
      PG_HOST: restaurant-postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: 1234
      PG_DB_NAME: restaurant_db
      JWT_SECRET: super_secret_jwt_key_adonis_user_service
    depends_on:
      - restaurant-postgres

volumes:
  restaurant_postgres_data:
