import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import User from 'App/Models/User'
import Address from 'App/Models/Address'
import { AddressStatus } from 'App/Constants/Status'

export default class AddressSeeder extends BaseSeeder {
  public async run() {
    const users = await User.all()

    const addressTemplates = [
      {
        label: 'HOME',
        houseNo: '101',
        street: '5th Avenue',
        area: 'Manhattan',
        city: 'New York',
        state: 'NY',
        pincode: '10001',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'WORK',
        houseNo: '202',
        street: 'Market Street',
        area: 'Downtown',
        city: 'San Francisco',
        state: 'CA',
        pincode: '94105',
        isDefault: false,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '303',
        street: 'Ocean Drive',
        area: 'South Beach',
        city: 'Miami',
        state: 'FL',
        pincode: '33139',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '404',
        street: 'Michigan Ave',
        area: 'Loop',
        city: 'Chicago',
        state: 'IL',
        pincode: '60601',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'WORK',
        houseNo: '505',
        street: 'Congress Ave',
        area: 'Downtown',
        city: 'Austin',
        state: 'TX',
        pincode: '78701',
        isDefault: false,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '606',
        street: 'Pike Street',
        area: 'Capitol Hill',
        city: 'Seattle',
        state: 'WA',
        pincode: '98101',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '707',
        street: 'Peachtree St',
        area: 'Midtown',
        city: 'Atlanta',
        state: 'GA',
        pincode: '30308',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'WORK',
        houseNo: '808',
        street: '17th Street',
        area: 'Financial Dist',
        city: 'Denver',
        state: 'CO',
        pincode: '80202',
        isDefault: false,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '909',
        street: 'Sunset Blvd',
        area: 'Hollywood',
        city: 'Los Angeles',
        state: 'CA',
        pincode: '90028',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '1010',
        street: 'Boylston St',
        area: 'Back Bay',
        city: 'Boston',
        state: 'MA',
        pincode: '02116',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'WORK',
        houseNo: '1111',
        street: 'Elm Street',
        area: 'Uptown',
        city: 'Dallas',
        state: 'TX',
        pincode: '75201',
        isDefault: false,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '1212',
        street: 'Broad Street',
        area: 'Center City',
        city: 'Philadelphia',
        state: 'PA',
        pincode: '19107',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '1313',
        street: 'Grand Ave',
        area: 'Downtown',
        city: 'Phoenix',
        state: 'AZ',
        pincode: '85003',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'WORK',
        houseNo: '1414',
        street: 'Main Street',
        area: 'River Quarter',
        city: 'Portland',
        state: 'OR',
        pincode: '97204',
        isDefault: false,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '1515',
        street: 'Las Vegas Blvd',
        area: 'Strip',
        city: 'Las Vegas',
        state: 'NV',
        pincode: '89109',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '1616',
        street: 'Canal Street',
        area: 'French Quarter',
        city: 'New Orleans',
        state: 'LA',
        pincode: '70112',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'WORK',
        houseNo: '1717',
        street: 'K Street',
        area: 'Downtown',
        city: 'Washington',
        state: 'DC',
        pincode: '20006',
        isDefault: false,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '1818',
        street: 'Broadway',
        area: 'Nashville West',
        city: 'Nashville',
        state: 'TN',
        pincode: '37203',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'HOME',
        houseNo: '1919',
        street: 'Nicollet Mall',
        area: 'Downtown',
        city: 'Minneapolis',
        state: 'MN',
        pincode: '55402',
        isDefault: true,
        status: AddressStatus.ENABLED,
      },
      {
        label: 'WORK',
        houseNo: '2020',
        street: 'Main St',
        area: 'Downtown',
        city: 'Salt Lake City',
        state: 'UT',
        pincode: '84101',
        isDefault: false,
        status: AddressStatus.ENABLED,
      },
    ]

    for (let i = 0; i < addressTemplates.length; i++) {
      const user = users[i % users.length]
      const addr = addressTemplates[i]

      const existing = await Address.query()
        .where('user_id', user.id)
        .where('street', addr.street)
        .first()

      if (!existing) {
        await Address.create({
          userId: user.id,
          label: addr.label,
          houseNo: addr.houseNo,
          street: addr.street,
          area: addr.area,
          city: addr.city,
          state: addr.state,
          pincode: addr.pincode,
          isDefault: addr.isDefault,
          status: addr.status,
        })
      }
    }
  }
}
